server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inventorydb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

inventory:
  simulate:
    latency-enabled: ${INVENTORY_LATENCY_ENABLED:true}
    max-latency-ms: ${INVENTORY_MAX_LATENCY_MS:2000}
    failure-rate: ${INVENTORY_FAILURE_RATE:0.20}

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4318}
  traces:
    sampler:
      probability: 1.0
  resource:
    attributes:
      service.name: inventory-service

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
